### ISSUE TITLE
[FEATURE REQUEST] Converting existing images in vault 

### ISSUE THREAD

**Issue by svrcek** [xRyul/obsidian-image-converter#16] opened 2023-09-30 16:23 UTC
Feature request:
It would be great to add the possibility of converting existing images in the vault and replacing the links with the proper file name in the notes.

The converter works perfectly; however, a user's vault can already have a huge size due to existing image files stored in less effective formats like .png. It is relatively easy to convert all image files with a script; however, all notes that refer to the converted image need to be updated as well.
Thank you for this great plugin!

**Comment by xRyul** [comment] 2023-09-30 22:32
thanks for checking out the plugin, you are not the first one requesting this now, thus going to have to look into it 😅

**Comment by xRyul** [comment] 2023-10-11 07:51
Closing as duplicate of https://github.com/xRyul/obsidian-image-converter/issues/7

Please continue conversation there.

**Closed by xRyul** 2023-10-11 07:51 UTC
