### ISSUE TITLE
[BUG] Sync icon constantly indicating sync

### ISSUE THREAD

**Issue by ThorstenRhau** [xRyul/obsidian-image-converter#126] opened 2024-12-19 10:14 UTC
<img width="37" alt="Screenshot 2024-12-19 at 10 37 08" src="https://github.com/user-attachments/assets/06655db2-267e-423d-967a-979548c3e583" />
The sync icon flashes between syncing and done while the plugin is disabled on Obsidian 1.7.7 running macOS. The sync log states "Fully synced"

Plugin version: 1.2.17

**Comment by xRyul** [comment] 2024-12-19 15:47
Do you know if this started happening only after upgrading to Obsidian 1.8? Also what dos the Sync Log say? 

<img width="154" alt="image" src="https://github.com/user-attachments/assets/208a7772-7b01-4004-bd01-b159d723bf9b" />

**Comment by esodesod** [comment] 2024-12-19 19:46
Hi! I can confirm issue with "flashing Obsidian Sync" icon (only) after upgrade to 1.8.0 (no other changes), and Image Converter 1.2.17, but Obsidian Sync has no changes (e..g still happens while Obsidian Sync is "fully synced").

Seems to be related to "cache cleanup", e.g. while opening developer tools, I see constant spamming of below messages

```
Automatic cache cleanup...
Cache cleanup time: 0.85107421875 ms
1 Cache cleaned: {}
```

<img width="1397" alt="image" src="https://github.com/user-attachments/assets/49cb3f7d-4da6-4241-a200-5f11b4dbe621" />

**Comment by xRyul** [comment] 2024-12-19 21:02
Thanks for the screenshot 🙏 Probably those excessive console logs will be the culprit, they are removed in future versions 🧹

Although, OP mentioned "while the plugin is disabled" which means either me or Obsidian is not unloading event listeners properly, so would need clarification from @ThorstenRhau what do they mean by that

**Comment by milosm** [comment] 2024-12-20 06:51
Hi! I had this happen with Obsidian 1.7.7 and Image Converter 1.2.17. It started happening after updating the plugin to this version.

**Comment by ThorstenRhau** [comment] 2024-12-20 07:25
> Thanks for the screenshot 🙏 Probably those excessive console logs will be the culprit, they are removed in future versions 🧹
> 
> Although, OP mentioned "while the plugin is disabled" which means either me or Obsidian is not unloading event listeners properly, so would need clarification from @ThorstenRhau what do they mean by that

When the plugin is disabled or uninstalled obsidian behaves as expected, no excessive logs, and the sync icon only shows syncing when actual files are synced, after that the icon shows a green check-mark indicating all-synced.

**Comment by xRyul** [comment] 2024-12-20 12:25
The cache cleanup was indeed the culprit. 
The default value was set in minutes, disregarding the fact that the actual calculation would be done in milliseconds. So the default 60 in essence was being interpreted as 0.001min - which was way too rapid. Should be fixed now.


Patched in [1.2.19](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.19)

**Comment by esodesod** [comment] 2024-12-20 18:38
Hi! Thanks for the swift response and fix here; I can confirm the cache cleanup "bug" is no longer is an issue in Obsidian 1.8.0, after updating to 1.2.19 **and** manually updating the auto-cleanup interval from 0.001 to 60 (not changed automatically).

**PS:** I don't know if it's possible to (automatically) write a partially default update (one-shot), or if the manual change is required by all users? Point being; maybe some users don't review the release notes, and never (manually) change the ato-cleanup interval value, hence it would be nice to automatically update the default (for this value), if possible. Anyways, thanks a million; really love this extensions, and your work here 🙌! Merry xmas 🎅.

**Comment by rubcap** [comment] 2024-12-20 20:23
I had noticed this too yesterday, didn't need to make a bug report ... fixed already 🙂. Thanks!

**Comment by xRyul** [comment] 2024-12-20 21:18
> Hi! Thanks for the swift response and fix here; I can confirm the cache cleanup "bug" is no longer is an issue in Obsidian 1.8.0, after updating to 1.2.19 **and** manually updating the auto-cleanup interval from 0.001 to 60 (not changed automatically).
> 
> **PS:** I don't know if it's possible to (automatically) write a partially default update (one-shot), or if the manual change is required by all users? Point being; maybe some users don't review the release notes, and never (manually) change the ato-cleanup interval value, hence it would be nice to automatically update the default (for this value), if possible. Anyways, thanks a million; really love this extensions, and your work here 🙌! Merry xmas 🎅.

That's a good point! 

That's because when Obsidian updates the plugin it keeps all plugin settings inside `data.json` 😭 usually that's a good thing, but not in this case.. so any default values which ship with the plugin would not get applied if that file already exists. Plugin reinstall would fix this, and it would create new clean `data.json` with all new defaults. But as you say, not everyone reads release notes.

Before I start implementing something more robust (like proper settings migration), I've pushed a quick mini update where I simply changed 1 variable name, which in theory now even if old `data.json` existed, the plugin would simply not know what to do with that old variable, and thus the new default would kick in. Merry xmas 🎅

**Closed** 2024-12-26 07:51 UTC
