### ISSUE TITLE
[BUG] Mobile: Obsidian Sync causes images to be reprocessed and breaks links

### ISSUE THREAD

**Issue by darribas** [xRyul/obsidian-image-converter#100] opened 2024-11-21 16:18 UTC
I'm using IC on an iPad, a Mac, and iPhone and a Windows laptop where I sync using Obsidian Sync. I have the plugin installed in all the devices. I have realised IC has started deleting an image that had been added (and processed) in one device when it gets synced to another device and is then processed then. The only setting I have changed on the plugin is to "replace" and output file if one already exists.

If this is intended behaviour, it is highly unintuitive why it does so. More importantly, how to work around it. Any ideas/suggestions?

**Comment by ckdanny** [comment] 2024-11-21 16:34
I encountered this issue as well. I was able to identify and restore the missing images by checking my Mega backup files.
This happens frequently when I added image via desktop and open my app on iOS, it then got removed.

**Comment by xRyul** [comment] 2024-11-21 21:09
> I'm using IC on an iPad, a Mac, and iPhone and a Windows laptop where I sync using Obsidian Sync. I have the plugin installed in all the devices. I have realised IC has started deleting an image that had been added (and processed) in one device when it gets synced to another device and is then processed then. The only setting I have changed on the plugin is to "replace" and output file if one already exists.
> 
> If this is intended behaviour, it is highly unintuitive why it does so. More importantly, how to work around it. Any ideas/suggestions?

Can you confirm if we are definitely dealing with images being re-processed during sync? That is an old bug which was temporarily around from 1.2.0 and fixed in 1.2.3. Multiple users confirmed it working with Obsidian Sync, Syncthing, and Remotely Save. Nothing in terms of drop/paste listeners was changed ever since. 

As for "Replace" yes it might and will remove images.

**Comment by darribas** [comment] 2024-11-21 22:47
Thanks so much for the quick reply @xRyul. A couple of follow up comments to help me understand:

> Can you confirm if we are definitely dealing with images being re-processed during sync? That is an old bug which was temporarily around from 1.2.0 and fixed in 1.2.3. Multiple users confirmed it working with Obsidian Sync, Syncthing, and Remotely Save. Nothing in terms of drop/paste listeners was changed ever since.

I'm not sure exactly what you mean by "re-processed" during sync. When I open Obsidian in a different device, I see update messages from Image Converter pop up that say the file is changed from a size <0kb to 0kb. When I check the Sync log, it shows up as deleted. If you have any specific ask, I can try to capture it on a screenshot or write the behaviour down more specifically.

> As for "Replace" - it will replace images, but wont replace all links where that image appears. Thus it might break links, and is not recommended for general use. Currently there is no simple way to refresh images inside notes via Obsidian API either. If Replace is selected it might take a few refreshes, and switching between notes until Obsidian re-renders them properly. Hence, when it finds image with the same filename which is being dropped/pasted, it will prioritise the new one - overwriting the old one. And that is also why some images might still appear fine, while in-fact they were already replaced and are just artefacts. Although, regardless, whether Rename or Replace is being used, they should not get triggered during sync.

So my understanding of "Replace" is that it'll find an image, whether previously processed or not, and will process it. If the output name that file should have got exists, it'll either replace the existing file ("Replace") or add a `-1`, etc. to the file name, creating effectively a separate file. My idea with using "Replace" is that, if they file exists, then it's linked on notes, replacing it with the same name would not affect the notes rendering it correctly. 

If that is not what it actually does (it sounds like that's the case), what'd you recommend that I use for similar behaviour? I just want the processed image (smaller footprint) _instead_ of the original one, but with the same location/name so it renders in the notes that were using the original one. And the original one gone.

Thank you so much for your support.

**Comment by xRyul** [comment] 2024-11-22 15:03
Looks like we are dealing with 2 problems here:

> ... I see update messages from Image Converter pop up that say the file is changed from a size <0kb to 0kb...

Sync. This should not be happening. Are you on 1.2.8 ? It seems like Obsidian Sync is triggering reinsertion of all images, thus consequently Image Converter reacts to it. It must be using something different from how remotely-save or syncthing works. My Obsidian Sync just run out, thus it will be hard to troubleshoot. 

- Can you confirm your Obsidian version, Image converter version and what are your paths for saving attachments? Both from within Obsidian Settings and Image converter plugin settings?
- Do you use any custom variables during filename or path creation? (Some combinations maybe are causing these "processing" loops, thus triggering notifications)
- Also do you keep all images in 1 master folder, or across multiple folders? 
- Do you reuse 1 image with the same name across multiple notes?

> ...I just want the processed image (smaller footprint)

a) If you just need to **_compress all images in any given note_**, you could simply run: CMD+P -> "Process all images in current note" -> Convert to WEBP, quality 75, resize mode: none. It will convert most image formats in current active note into WEBP and compress them too = smaller file size (smaller footprint?). I assume that is the behaviour you expect, but for single image drops? 

b) If you want to recompress (and/or resize) **_only single image_** which is **already** in the note.  Change "If an output file already exists" to "Rename". Copy into clipboard -> delete the original file -> paste it back into the note so that Image Converter could compress it and rename following any convention you describe in the settings (e.g.: use {noteName} to rename image to the note where it was dropped into or {imageName} to keep image name instead of default obsidian "pasted images..." ). Or if you know where that file in the system, you could just drop it into Obsidian note where it was located, thus triggering image converter which would consequently compress and convert it as needed.

>  ..so it renders in the **notes** that were using the original one

FYI: If you have one image linked in multiple locations across the vault, this is bad practice and shouldn't be done.

**Comment by ckdanny** [comment] 2024-11-22 16:52
I can share what i captured and it is very to reproduce
1. Image inserted in desktop client
2. fully obsidian sync
3. Open mobile client
Recording: https://app.filen.io/#/d/41a07864-16a6-4f80-8bcc-3779c6825563#B9XvgiUImQbJsriRBPUQqfuVGkgzjRc9

And then the progress below at the end stuck, and refresh the page in either desktop and mobile, the image is gone, 
<img width="302" alt="image" src="https://github.com/user-attachments/assets/6155d588-2d62-45cc-b33e-391480a8d2c8">

**Comment by xRyul** [comment] 2024-11-22 17:40
Thanks, this helps. 

Do those popup messages only appear on mobile?

**Comment by ckdanny** [comment] 2024-11-22 17:42
From my observations, this issue only occurs on mobile devices, while the desktop version works pretty well.

**Comment by Ai-Jani** [comment] 2024-11-24 09:36
I have the same problem (since I upgraded Image Converter from v1.2.6 to v1.2.8).

I use two Android devices and one PC, and I sync them with Sync, and back up the PC to GitHub with Git.

When I send any image changes to the Android device via Sync, a similar pop-up message appears and the original image file is deleted. Then the renamed and compressed image is placed in the Root folder.
When the PC receives this change via Sync, the original image is actually deleted and the new image is in the Root folder. After this, if I use the Git function to discard and return to the original state and send this change to the Android device, the same problem occurs again.

When I use Obsidian on two Android devices synced with Sync, an infinite loop occurs in which they send changes to each other, and an infinite number of images with `-1` at the end are generated.

**Comment by Ai-Jani** [comment] 2024-11-24 14:53
Although a little late, I would like to express my gratitude for this project. I understand your situation and would like to help in any way I can.

> Does the issue appear when you pull from git with Sync disabled? I use git on iPad, iPhone, Windows PC, Mac and never run into this issue. 

Sorry, I use Git only on PC and Android only sync with Sync.

> 1. Update the main.js file: This might fix the issue. You can replace the existing file with the updated one here main.zip

I replaced main.js and still had the same problem.

> 2. Roll back to a previous version: If updating main.js doesn't work, you can temporarily switch back to version 1.1.7

After downloading and replacing main.js and manifest.json from v1.1.7, the problem disappeared!

***

For testing purposes, I created a new Vault, installed only Image Converter(v1.2.8), and used Sync to sync my PC and Android to try out various things. With Obsidian running on both my PC and Android, I confirmed that when I pasted an image on one device, the other device's Image Converter also processed it and uploaded a new file, and then an infinite loop ensued. At this time, both Image Converters output popup messages one after another. If turn off either Image Converter, the loop stops.

I will continue to look into this issue from tomorrow onwards.
Thank you.

**Comment by xRyul** [comment] 2024-11-24 18:31
> Although a little late, I would like to express my gratitude for this project. I understand your situation and would like to help in any way I can.
> 
> > Does the issue appear when you pull from git with Sync disabled? I use git on iPad, iPhone, Windows PC, Mac and never run into this issue.
> 
> Sorry, I use Git only on PC and Android only sync with Sync.
> 
> > 1. Update the main.js file: This might fix the issue. You can replace the existing file with the updated one here main.zip
> 
> I replaced main.js and still had the same problem.
> 
> > 2. Roll back to a previous version: If updating main.js doesn't work, you can temporarily switch back to version 1.1.7
> 
> After downloading and replacing main.js and manifest.json from v1.1.7, the problem disappeared!
> 
> For testing purposes, I created a new Vault, installed only Image Converter(v1.2.8), and used Sync to sync my PC and Android to try out various things. With Obsidian running on both my PC and Android, I confirmed that when I pasted an image on one device, the other device's Image Converter also processed it and uploaded a new file, and then an infinite loop ensued. At this time, both Image Converters output popup messages one after another. If turn off either Image Converter, the loop stops.
> 
> I will continue to look into this issue from tomorrow onwards. Thank you.

I managed to reproduce some of the behaviour you describe by simulating various file creation/modification scenarios using Obsidian API (instead of OS). By quickly creating, adding removing images to and from Obsidian - pop-up messages indeed appeared. 

Although if that fixes actual Obsidian Sync issue still not sure,  feel free to test it: [main-1.2.9.zip](https://github.com/user-attachments/files/17894385/main-1.2.9.zip)

**Comment by danny-tree3health** [comment] 2024-11-24 23:43
Thanks @xRyul for your quick response. 
From my basic testing on 1.2.9, the problem seems resolved but the sync record shows some strange behaviour that data.json keep sync (change?) in the background. 

<img src="https://github.com/user-attachments/assets/abb32583-9e77-4a60-b2db-14929ffbcce1" width=350 />

**Comment by Ai-Jani** [comment] 2024-11-25 01:26
Thank you! I also tried v1.2.9.

When pasting an image on mobile, it was only processed on the mobile side and only downloaded on the PC.
However, when pasting an image on a PC, it seems to be processed on the PC side and then on the mobile side as well.

In my case the data.json issue did not occur.

**Comment by xRyul** [comment] 2024-11-25 14:16
Thanks, @danny-tree3health  and @Ai-Jani your description helps. 

Please try update via Community Plugins to 1.2.9 and let me know if JSON issue still appears. 

As for:
>...when pasting an image on a PC, it seems to be processed on the PC side and then on the mobile side as well.

I still going to have to debug it more.

**Comment by xRyul** [comment] 2024-11-26 22:20
Please update to [1.2.10](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.10). Don't forget to relaunch IC and Obsidian on mobile. 

PC to Mobile should no longer trigger reprocessing.

**Comment by Ai-Jani** [comment] 2024-11-27 02:14
I tested v1.2.10, and after pasting an image, it was properly processed only once! (Both from PC to Mobile and from Mobile to PC)

I think all the problems I had in my environment have been resolved.
Thanks so much. I respect @xRyul 's work!

**Comment by Ai-Jani** [comment] 2024-11-27 02:52
Sorry, I found a new bug.

When the settings are as below, if I paste an image, a message like "xxx KB -> 0 B (-100.0%)" will pop up and the image will be deleted (The image file itself is actually deleted).
- "Convert to": "Same as original" or Same as the actual image pasted
- "Output Location": "Default"
- "File Naming": "Keep original name"

If even one of the conditions does not match, this problem does not occur. It seems that this problem occurs when the path, file name, and extension of "original" and "output" match.

This issue occurs on both PC and Android. Sync isn't even involved. (it may be a different issue)

**Closed** 2024-11-27 11:40 UTC
